import { Member, Event, Article, Partner, Founder } from './types';
import { MOCK_GALLERY_IMAGES } from './gallery-constants';

export const NAV_LINKS = [
  { name: 'Accueil', path: '/' },
  { name: 'À propos', path: '/a-propos' },
  { name: 'Membres', path: '/membres' },
  { name: 'Événements', path: '/evenements' },
  { name: 'Actualités', path: '/actualites' },
  { name: 'Partenaires', path: '/partenaires' },
  { name: 'Galerie', path: '/galerie' },
  { name: 'Contact', path: '/contact' },
];

const assignRandomImage = () => MOCK_GALLERY_IMAGES[Math.floor(Math.random() * MOCK_GALLERY_IMAGES.length)];

export const MOCK_MEMBERS: Member[] = [
  { id: 1, name: 'EYANG NDONG Dona Pascale', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 2, name: 'Louis Parfait Nguema Asseko', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 3, name: 'Koyo soma Rudy Graziella', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 4, name: 'Amoussou kokou Herlose', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 5, name: 'NDOH ZOMO Lesly Myriam', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 6, name: 'Epouta Angèle', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 7, name: 'Missogni Moïse', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 8, name: 'Duchesse GAYAKPA', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 9, name: 'Mbazoghe bekale latifa nynelle', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 10, name: 'N’NOH Rebecca stecy', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 11, name: 'Venusia Olery', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 12, name: 'Minkoue mi ndong Stecya Yvonne deurda', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 13, name: 'OKOME HOUSSA Sephora Nawelle', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 14, name: 'MBA NGUEMA Etienne janvier', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 15, name: 'BOUABE MOUSSAVOU Germain Stéphane', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 16, name: 'Evrad Mouiri Pendi', category: 'Esthétique & Maquillage', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 17, name: 'BIVONGA Monica Francès', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 18, name: 'PEA Emma Claudia', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 19, name: 'LENGOUMOU KENGUE Sylvaine Rhaïna', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 20, name: 'PAMBOU DIHIBA Aimée Jeanlicia', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 21, name: 'Bernadette Mpaga Tchandi', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 22, name: 'BENDJA MADAMA Luce kerenne hurielle', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 23, name: 'Akile Tabarna', category: 'Événementiel', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 24, name: 'MEKUI M\'ESSONO lea Daniel', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 25, name: 'Tito Anselme mahutin', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 26, name: 'NTEME NZE Brice', category: 'Événementiel', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 27, name: 'Nkowan Metoughe Amandine Odette', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 28, name: 'Nyambhat Mendome xenia riopelle', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 29, name: 'Ntutum Nancy Marlène', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 30, name: 'Medame Mba Mirabelle', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 31, name: 'Létiana BONGO', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 32, name: 'Hodonou Viededjiena Turbice', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 33, name: 'Jean Jacques Melvin KANGUE', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 34, name: 'NGA OZOUNGUE', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 35, name: 'Angue bilanga Shéronne', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 36, name: 'DIOMBE VANDA - KOMBA Kristina - Pascale', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 37, name: 'ANGUE NKIZOGO sabrina xavière', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 38, name: 'BITO MINSO ANNE-CHLOÉ', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 39, name: 'Ikinda mengue keshia Elsie', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 40, name: 'NZAÏ Freid', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 41, name: 'Tibé eny adjoua Kevinath', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 42, name: 'OBONO KOUAMÉ Maryse Karen', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 43, name: 'NYACKAT DOUCKAGA BRANDON', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 44, name: 'Coulibaly Souleymane', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 45, name: 'Ntsame ekogha Christmela jemima', category: 'Esthétique & Maquillage', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 46, name: 'Ada Nze ETOUGHE Claude Christine', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 47, name: 'OZIMO OSCAR RAYMOND ANTOINE', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 48, name: 'AKENG Jennifer', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 49, name: 'Jaria Bakou', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 50, name: 'ANDEME ESSONO ROLIE', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 51, name: 'Marvine Assélé', category: 'Petites mains', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 52, name: 'MBOULA Guibinga Hugue Arnaud', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 53, name: 'Janellia KOUMBA', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 54, name: 'Abogho Mapaga Cirlie A.', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 55, name: 'Ngondi Mangouhou Anna Jessy Belgrace', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 56, name: 'Greg Mbourou', category: 'Accessoiriste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 57, name: 'Mukag-Mueng Zihou Charles Ronny', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 58, name: 'MUGUNDE MBINE Amena Princess', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 59, name: 'BENBO KOUTOI BENBO ERIC Henderson', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 60, name: 'NYAMETE TOWENE Ruth jussy', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 61, name: 'BONOUKPO ANANI DONATIEN', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 62, name: 'Ada Osseni Aïcha Sarah Tendresse', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 63, name: 'Nzamba Diabaté trifene elkana Morgan', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 64, name: 'NTSAME MUNGUENGUI Eunice Hanska', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 65, name: 'Okamba Pembe Annie flore', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 66, name: 'M\'badingue mboumbe john dick dimourim', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 67, name: 'AVOMO MEZUI PRISCILIA FLORENCE', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 68, name: 'Ekovonne Melissa', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 69, name: 'NZIENGUI PAULA VANELLA STELLA', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 70, name: 'Nzamba Grâce Oriane', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 71, name: 'OBAGO OVONO Ivana', category: 'Accessoiriste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 72, name: 'LOEMBA Gentricia epouse MOUNDEMBA', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 73, name: 'Dipsi Boswell Jr', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 74, name: 'Dibault Anna-Paule', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 75, name: 'MIKOLO MIA MAPOUKOU Cemen Gervelin', category: 'Événementiel', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 76, name: 'MUADI EKOLE Marthe', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 77, name: 'MISSOUWA-MOUNDOUMOU-Emmanuella-Grace', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 78, name: 'Njaki Roland', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 79, name: 'MOUDOUMA IKAPI SLLAS DOGIS', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 80, name: 'Nang Mintsa Therane chancy', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 81, name: 'Blaise Darciel MBA-NZOGHE', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 82, name: 'Eya Biyoghe Emmanuel Rosly', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 83, name: 'OGOULIGUENDE JULES ARISTIDE', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 84, name: 'Obone Eheppat kelda brundoline', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 85, name: 'ENGONE NGUEMA l\'or kensy', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 86, name: 'OMVOGUE DIVASSA GERMAIN', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 87, name: 'VALENTIN CEDRIQUE Ogwerowo Ondo Ogouamba', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 88, name: 'AKANDA NDONG DESIRE', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 89, name: 'Zinga malamba Nadine', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 90, name: 'Akouété Adevi Pauline', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 91, name: 'LEPENGUE BACKITA WILCY MARCELA', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 92, name: 'OTHA OYINAMONO FALK ABIUD', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 93, name: 'Kiende Mayombo Van Emmanuel', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 94, name: 'Ebang nguema briknex phalendry', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 95, name: 'OMBEMBE Olga Émilie claire pseudonyme Roxane', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 96, name: 'AZIZET - Phiras', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 97, name: 'KOUWAYE Tryphène Biliver Rachel', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 98, name: 'Mandoukou matoumba God Given', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 99, name: 'Onwuedo Eric', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 100, name: 'MBOUROU NGWELET GRAÏSHA', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 101, name: 'RETOA AVIKA Dackin Jamal', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 102, name: 'TOLE FORTUNÉ', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 103, name: 'Tami Oceandy William', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 104, name: 'Brigitte Nsie Nami', category: 'Accessoiriste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 105, name: 'Mbia Jeanne Liliane', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 106, name: 'MINKUE-NWACHUKWU-Salomé-léoncia', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 107, name: 'NIOMBA SIMA Elvy Wydna Claudia', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 108, name: 'Léna BISA', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 109, name: 'Dorinex Mboumba', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 110, name: 'Tamaga Eudouarda shelda', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 111, name: 'MAROUNDOU NDIMINA Leïla Monica Josy', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 112, name: 'Yembangoyi joyce Thusdin', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 113, name: 'YEZDAD Désigns', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 114, name: 'Idiata MISSIENDZOU vanessa Xavière', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 115, name: 'Linous katoch', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 116, name: 'Aisha yamav', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 117, name: 'MOUTSINGA Vénus Claude', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 118, name: 'RADEGAS Raïssa Radé', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 119, name: 'MEHEKOU MOULOUNGUI CONSTALIDA ORTY', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 120, name: 'RAIVAUD Paule Maroussia', category: 'Événementiel', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 121, name: 'Ntogolo Radega Aldrin', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 122, name: 'NGOLA RIABA Juniorra Odette', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 123, name: 'Jérémie Diop', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 124, name: 'Jacques Simon BEKALE ONDO', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 125, name: 'Hamed Dick', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 126, name: 'Alves Nunez linda épouse Remichi', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 127, name: 'Lenny Christelle ARONDO', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 128, name: 'Mbadinga Traoré Mamadou Yvane', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 129, name: 'Mbeng ndong Angelina constance', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 130, name: 'Ossavou koudouli Colitta veghalia', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 131, name: 'Doutsona Damila Olmige', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 132, name: 'Zang Nguema Ornichou', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 133, name: 'Scott Anderson', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 134, name: 'Mouanda Mouanda Line Vanessa', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 135, name: 'Moutsinga Yan', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 136, name: 'Mayila junior kegheni', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 137, name: 'Micky IBINDA', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 138, name: 'Ada Osseni Sarah Tendresse', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 139, name: 'Bella Mossangue Immaculée Noelie', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 140, name: 'LAWSON - BODY Messan Romeo', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 141, name: 'Maganga indjele esther Tricia', category: 'Esthétique & Maquillage', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 142, name: 'Nkoo Ndong', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 143, name: 'OBAME NGUEMA Christian', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 144, name: 'Moctar Bah', category: 'Styliste & Modéliste', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 145, name: 'Monkoun Irina', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 146, name: 'ADZODIE BINOUETA Léda Gracia Laurette', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 147, name: 'DIWA ELYARD GLENN MBAYA', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 148, name: 'Karabenta Moussa', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 149, name: 'Nsafou Diedrich Francel', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 150, name: 'ISSANGA OZOUMET Cladissa', category: 'Esthétique & Maquillage', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 151, name: 'Mabialadan', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
  { id: 152, name: 'NGOME-NKOGHE Grace-Wildine Axelle', category: 'Mannequin', bio: 'Acteur passionné de la mode gabonaise.', imageUrl: assignRandomImage(), socials: {} },
];

export const MOCK_EVENTS: Event[] = [
  { id: 1, title: 'Libreville Fashion Week', date: '22-25 NOV 2024', location: 'Radisson Blu, Libreville', description: 'Le rendez-vous incontournable de la mode gabonaise.', imageUrl: MOCK_GALLERY_IMAGES[6] },
  { id: 2, title: 'Workshop: De la création à la commercialisation', date: '15 OCT 2024', location: 'Institut Français, Libreville', description: 'Apprenez les clés du succès pour votre marque de mode.', imageUrl: MOCK_GALLERY_IMAGES[7] },
  { id: 3, title: 'Salon des Créateurs Émergents', date: '05 DÉC 2024', location: 'Jardin Botanique, Libreville', description: 'Découvrez les talents de demain et leurs créations uniques.', imageUrl: MOCK_GALLERY_IMAGES[8] },
];

export const MOCK_ARTICLES: Article[] = [
  { id: 1, title: 'Tendance 2024: Le retour du pagne tissé', excerpt: 'Explorez comment les designers gabonais réinventent cet héritage textile avec audace et modernité.', content: '<p>Explorez comment les designers gabonais réinventent cet héritage textile avec audace et modernité.</p>', imageUrl: MOCK_GALLERY_IMAGES[9], category: 'Tendances', date: '12 JUIL 2024' },
  { id: 2, title: 'Interview avec Franck Evina, icône de la mode', excerpt: 'Le fondateur de la marque "Racines" partage son parcours inspirant et sa vision pour l\'avenir de la mode africaine.', content: '<p>Le fondateur de la marque "Racines" partage son parcours inspirant et sa vision pour l\'avenir de la mode africaine.</p>', imageUrl: MOCK_GALLERY_IMAGES[10], category: 'Interviews', date: '08 JUIL 2024' },
  { id: 3, title: 'FEGAMOD annonce ses nouveaux partenariats', excerpt: 'La fédération s\'associe à des acteurs majeurs pour renforcer le soutien aux créateurs locaux et leur visibilité.', content: '<p>La fédération s\'associe à des acteurs majeurs pour renforcer le soutien aux créateurs locaux et leur visibilité.</p>', imageUrl: MOCK_GALLERY_IMAGES[11], category: 'Communiqués', date: '01 JUIL 2024' },
];

export const MOCK_FOUNDERS: Founder[] = [
    { id: 1, name: 'Ali Bongo Ondimba', title: 'Président d\'Honneur', imageUrl: MOCK_GALLERY_IMAGES[12] },
    { id: 2, name: 'Sylvia Bongo Ondimba', title: 'Marraine de la FEGAMOD', imageUrl: MOCK_GALLERY_IMAGES[13] },
    { id: 3, name: 'Franck Sima', title: 'Président', imageUrl: 'https://scontent.flbv4-1.fna.fbcdn.net/v/t39.30808-6/473677977_9128296503952662_8897451079006998067_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=6ee11a&_nc_eui2=AeF15cwlhZa3g07xq8eJZJn_0kSjya3bNOHSRKPJrds04ShhLQu6TtldL5jFLqDcu7ESrlXo6BRF8_GsYUW-19SI&_nc_ohc=YqYKcRYF5DAQ7kNvwHWSaUe&_nc_oc=Adned4RCPgvNp4Q5mvomLWNxgz2jSsDHSMXjFHVXZYcxS6lOSlxFdEbJXvHsH700q30&_nc_zt=23&_nc_ht=scontent.flbv4-1.fna&_nc_gid=tAF9UE47VMF8_0c2QO1M2g&oh=00_AfYfSzd3BQt0PGZwDFqjM-hYsZviBMMzICyf6U-AtKE1yA&oe=68BECA2C' },
    { id: 4, name: 'Jessica Moubamba', title: 'Vice-Présidente', imageUrl: MOCK_GALLERY_IMAGES[14] },
];

export const MOCK_PARTNERS: Partner[] = [
  { id: 1, name: 'Gabon Telecom', logoUrl: MOCK_GALLERY_IMAGES[15] },
  { id: 2, name: 'Airtel Gabon', logoUrl: MOCK_GALLERY_IMAGES[16] },
  { id: 3, name: 'BGFI Bank', logoUrl: MOCK_GALLERY_IMAGES[17] },
  { id: 4, name: 'Ministère de la Culture', logoUrl: MOCK_GALLERY_IMAGES[18] },
  { id: 5, name: 'Institut Français', logoUrl: MOCK_GALLERY_IMAGES[19] },
];